apiVersion: apps/v1         # apiserver的版本
kind: Deployment            # 副本控制器deployment，管理pod和RS
metadata:
  name: discuz              # deployment的名称，全局唯一
spec:
  replicas: 1               # Pod副本期待数量
  selector:
    matchLabels:            # 定义RS的标签
      app: discuz           # 符合目标的Pod拥有此标签
  strategy:                 # 定义升级的策略
    type: RollingUpdate     # 滚动升级，逐步替换的策略
  template:                 # 根据此模板创建Pod的副本（实例）
    metadata:
      labels:
        app: discuz         # Pod副本的标签，对应RS的Selector
    spec:
      containers:           # Pod里容器的定义部分
        - name: discuz      # 容器的名称
          image: skyzhou/docker-discuz
          ports:
            - containerPort: 80
          env:              # 写入到容器内的环境容量
            - name: MYSQL_PORT_3306_TCP
              value: 10.3.254.103:3306
            - name: DISCUZ_DB_PASSWORD
              value: root

